# version: "3.8"
services:
  service_users:
    build: ./service_users
    container_name: service_users
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./service_users:/app
    restart: unless-stopped

  service_orders:
    build: ./service_orders
    container_name: service_orders
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=development
    volumes:
      - ./service_orders:/app
    restart: unless-stopped

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - USERS_URL=http://service_users:8001
      - ORDERS_URL=http://service_orders:8002
    depends_on:
      - service_users
      - service_orders
    volumes:
      - ./api_gateway:/app
    restart: unless-stopped
